version: "3.8"

services:
  test-app:
    build: ./
    command: ./test-app
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_HOST: db
      DB_PORT: 5432

  db:
    restart: unless-stopped
    image: postgres:13
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5436:5432"

volumes:
  postgres_data:
    driver: local